"""
Document exporters (Sprint 7+) — professional PDF reports and Excel workbooks.

Used by the BOQ generator (Sprint 7), carbon LCA (Sprint 8), submission
packages (Sprint 10), validation reports (Sprint 11) and certificates
(Sprint 13). ``reportlab`` / ``openpyxl`` are imported lazily so the API can
boot and be tested without them installed.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence

log = logging.getLogger("imad.exports")


class ExportError(Exception):
    """Raised when a report cannot be generated."""


def exports_dir() -> Path:
    from app.core.storage import storage_root

    p = storage_root() / "exports"
    p.mkdir(parents=True, exist_ok=True)
    return p


def now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _fmt(value: Any, digits: int = 2) -> str:
    if isinstance(value, (int, float)):
        return f"{value:,.{digits}f}"
    return str(value)


# ══════════════════════════════════════════════════════════════ Excel ──────
def build_workbook(path: str | Path, sheets: Sequence[tuple[str, str, List[List[Any]]]]) -> Path:
    """Write an .xlsx workbook.

    ``sheets`` is an ordered iterable of ``(sheet_name, intro_line, rows)``;
    the first row of ``rows`` is treated as the header row.
    """
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
        from openpyxl.utils import get_column_letter
    except ImportError as exc:  # pragma: no cover
        raise ExportError("openpyxl is required for Excel export") from exc

    wb = Workbook()
    wb.remove(wb.active)
    header_fill = PatternFill("solid", fgColor="0A5C36")
    gold_fill = PatternFill("solid", fgColor="C9A227")
    header_font = Font(color="FFFFFF", bold=True)
    thin = Side(style="thin", color="D0D5DD")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)

    for name, intro, rows in sheets:
        ws = wb.create_sheet(title=name[:31])
        ws.append([intro])
        ws["A1"].font = Font(bold=True, size=13, color="0A5C36")
        ws.append([f"Generated by Imad · {now_iso()}"])
        ws.append([])
        for r_i, row in enumerate(rows):
            ws.append(row)
            excel_r = r_i + 4
            if r_i == 0:
                for c in range(1, len(row) + 1):
                    cell = ws.cell(row=excel_r, column=c)
                    cell.fill = header_fill
                    cell.font = header_font
                    cell.border = border
                    cell.alignment = Alignment(horizontal="center")
            else:
                for c in range(1, len(row) + 1):
                    cell = ws.cell(row=excel_r, column=c)
                    cell.border = border
                    if isinstance(row[c - 1], (int, float)):
                        cell.number_format = "#,##0.00"
            if str(row[0]).startswith("TOTAL"):
                for c in range(1, len(row) + 1):
                    ws.cell(row=excel_r, column=c).fill = gold_fill
        # sensible widths
        _widths: dict = {}
        for row in rows:
            for cdx, val in enumerate(row, start=1):
                _widths[cdx] = min(max(_widths.get(cdx, 10), len(str(val)) + 2), 52)
        for cdx, w in _widths.items():
            ws.column_dimensions[get_column_letter(cdx)].width = w
        ws.freeze_panes = "A5"

    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    wb.save(out)
    log.info("Workbook written: %s", out)
    return out


# ════════════════════════════════════════════════════════════════ PDF ──────
_BRAND_GREEN = "#0A5C36"
_BRAND_GOLD = "#C9A227"


def _pdf_styles():
    from reportlab.lib import colors
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet

    base = getSampleStyleSheet()
    styles = {
        "title": ParagraphStyle(
            "ImadTitle", parent=base["Title"], textColor=colors.HexColor(_BRAND_GREEN)),
        "h2": ParagraphStyle(
            "ImadH2", parent=base["Heading2"], textColor=colors.HexColor(_BRAND_GREEN),
            spaceBefore=14, spaceAfter=6),
        "body": ParagraphStyle("ImadBody", parent=base["BodyText"], fontSize=9.5, leading=13),
        "small": ParagraphStyle(
            "ImadSmall", parent=base["BodyText"], fontSize=8, leading=11,
            textColor=colors.HexColor("#475467")),
    }
    return colors, styles


def _pdf_header_footer(canvas, doc):
    """Shared page furniture: brand rule + footer with page numbers."""
    from reportlab.lib import colors

    canvas.saveState()
    w, h = doc.pagesize
    canvas.setStrokeColor(colors.HexColor(_BRAND_GOLD))


def build_pdf_report(path: str | Path, title: str, subtitle: str = "",
                     sections: Iterable[tuple[str, List[List[Any]], Optional[str]]] = (),
                     meta_rows: Optional[List[List[Any]]] = None,
                     summary_box: Optional[Dict[str, Any]] = None,
                     chart_drawing=None) -> Path:
    """Generic branded PDF report.

    ``sections`` yields ``(heading, table_rows, note)`` triples; the first row
    of each ``table_rows`` is the styled header row. ``summary_box`` renders a
    highlighted KPI block on the cover; ``chart_drawing`` (a reportlab Drawing)
    is appended after it when provided.
    """
    try:
        from reportlab.lib import colors
        from reportlab.lib.enums import TA_CENTER
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle
        from reportlab.platypus import (
            Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
        )
    except ImportError as exc:  # pragma: no cover
        raise ExportError("reportlab is required for PDF export") from exc

    _, styles = _pdf_styles()
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)

    story: List[Any] = [Paragraph(title, styles["title"])]
    if subtitle:
        story.append(Paragraph(subtitle, ParagraphStyle(
            "sub", parent=styles["body"], alignment=TA_CENTER, spaceAfter=10)))
    if meta_rows:
        meta = Table([[str(c) for c in row] for row in meta_rows], colWidths=[150, 330])
        meta.setStyle(TableStyle([
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        story += [Spacer(1, 6), meta]
    if summary_box:
        kpi_rows = [[k, _fmt(v)] for k, v in summary_box.items()]
        kpi = Table(kpi_rows, colWidths=[240, 150])
        kpi.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#ECFDF3")),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor(_BRAND_GREEN)),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
        ]))
        story += [Spacer(1, 12), kpi]
    if chart_drawing is not None:
        story += [Spacer(1, 12), chart_drawing]

    for heading, rows, note in sections:
        story.append(Paragraph(heading, styles["h2"]))
        if not rows:
            story.append(Paragraph("No data available.", styles["body"]))
            continue
        data = [[str(c) for c in rows[0]]] + [
            [_fmt(c) for c in row] for row in rows[1:]]
        table = Table(data, repeatRows=1)
        style = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(_BRAND_GREEN)),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#D0D5DD")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1),
             [colors.white, colors.HexColor("#F5F7FA")]),
            ("TOPPADDING", (0, 0), (-1, -1), 3.5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3.5),
        ]
        for r_i, row in enumerate(rows):
            if str(row[0]).startswith(("TOTAL", "Σ")):
                style.append(("BACKGROUND", (0, r_i), (-1, r_i),
                              colors.HexColor("#FEF6DE")))
                style.append(("FONTNAME", (0, r_i), (-1, r_i), "Helvetica-Bold"))
        table.setStyle(TableStyle(style))
        story.append(table)
        if note:
            story.append(Spacer(1, 4))
            story.append(Paragraph(note, styles["small"]))

    doc = SimpleDocTemplate(
        str(out), pagesize=A4, topMargin=58, bottomMargin=44,
        leftMargin=40, rightMargin=40, title=title)
    doc.build(story, onFirstPage=_pdf_header_footer, onLaterPages=_pdf_header_footer)
    log.info("PDF written: %s", out)
    return out


def simple_bar_chart(title: str, series: Sequence[tuple[str, float]],
                     unit: str = "", width: int = 480, height: int = 260):
    """Return a reportlab Drawing bar chart for embedding into PDF reports."""
    try:
        from reportlab.graphics.charts.barcharts import VerticalBarChart
        from reportlab.graphics.shapes import Drawing, String
        from reportlab.lib import colors
    except ImportError as exc:  # pragma: no cover
        raise ExportError("reportlab is required for charts") from exc

    d = Drawing(width, height)
    chart = VerticalBarChart()
    chart.x, chart.y, chart.width, chart.height = 55, 40, width - 80, height - 80
    chart.data = [[float(v) for _, v in series]]
    chart.categoryAxis.categoryNames = [k for k, _ in series]
    chart.categoryAxis.labels.fontName = "Helvetica"
    chart.categoryAxis.labels.fontSize = 7
    chart.valueAxis.valueMin = 0
    chart.valueAxis.valueMax = max([float(v) for _, v in series] or [1]) * 1.25
    chart.valueAxis.labels.fontName = "Helvetica"
    chart.valueAxis.labels.fontSize = 7
    chart.bars.fillColor = colors.HexColor(_BRAND_GREEN)
    chart.barLabels.fontName = "Helvetica"
    chart.barLabels.fontSize = 7
    chart.barLabelFormat = "%.0f"
    d.add(chart)
    if unit:
        d.add(String(55, height - 22, f"Values in {unit}",
                     fontName="Helvetica-Oblique", fontSize=8))
    return d