"""
Document exporters (Sprint 7+) — professional PDF reports and Excel workbooks.

Used by the BOQ generator (Sprint 7), carbon LCA (Sprint 8), submission
packages (Sprint 10), validation reports (Sprint 11) and certificates
(Sprint 13). ``reportlab`` / ``openpyxl`` are imported lazily so the API can
boot and be tested without them installed.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence

log = logging.getLogger("imad.exports")


class ExportError(Exception):
    """Raised when a report cannot be generated."""


def exports_dir() -> Path:
    from app.core.storage import storage_root

    p = storage_root() / "exports"
    p.mkdir(parents=True, exist_ok=True)
    return p


def now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _fmt(value: Any, digits: int = 2) -> str:
    if isinstance(value, (int, float)):
        return f"{value:,.{digits}f}"
    return str(value)


# ══════════════════════════════════════════════════════════════ Excel ──────
def build_workbook(path: str | Path, sheets: Sequence[tuple[str, str, List[List[Any]]]]) -> Path:
    """Write an .xlsx workbook.

    ``sheets`` is an ordered iterable of ``(sheet_name, intro_line, rows)``;
    the first row of ``rows`` is treated as the header row.
    """
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
        from openpyxl.utils import get_column_letter
    except ImportError as exc:  # pragma: no cover
        raise ExportError("openpyxl is required for Excel export") from exc

    wb = Workbook()
    wb.remove(wb.active)
    header_fill = PatternFill("solid", fgColor="0A5C36")
    gold_fill = PatternFill("solid", fgColor="C9A227")
    header_font = Font(color="FFFFFF", bold=True)
    thin = Side(style="thin", color="D0D5DD")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)

    for name, intro, rows in sheets:
        ws = wb.create_sheet(title=name[:31])
        ws.append([intro])
        ws["A1"].font = Font(bold=True, size=13, color="0A5C36")
        ws.append([f"Generated by Imad · {now_iso()}"])
        ws.append([])
        for r_i, row in enumerate(rows):
            ws.append(row)
            excel_r = r_i + 4
            if r_i == 0:
                for c in range(1, len(row) + 1):
                    cell = ws.cell(row=excel_r, column=c)
                    cell.fill = header_fill
                    cell.font = header_font
                    cell.border = border
                    cell.alignment = Alignment(horizontal="center")
            else:
                for c in range(1, len(row) + 1):
                    cell = ws.cell(row=excel_r, column=c)
                    cell.border = border
                    if isinstance(row[c - 1], (int, float)):
                        cell.number_format = "#,##0.00"
            if str(row[0]).startswith("TOTAL"):
                for c in range(1, len(row) + 1):
                    ws.cell(row=excel_r, column=c).fill = gold_fill
        # sensible widths
        _widths: dict = {}
        for row in rows:
            for cdx, val in enumerate(row, start=1):
                _widths[cdx] = min(max(_widths.get(cdx, 10), len(str(val)) + 2), 52)
        for cdx, w in _widths.items():
            ws.column_dimensions[get_column_letter(cdx)].width = w
        ws.freeze_panes = "A5"

    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    wb.save(out)
    log.info("Workbook written: %s", out)
    return out


# ════════════════════════════════════════════════════════════════ PDF ──────
_BRAND_GREEN = "#0A5C36"
_BRAND_GOLD = "#C9A227"


def _pdf_styles():
    from reportlab.lib import colors
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet

    base = getSampleStyleSheet()
    styles = {
        "title": ParagraphStyle(
            "ImadTitle", parent=base["Title"], textColor=colors.HexColor(_BRAND_GREEN)),
        "h2": ParagraphStyle(
            "ImadH2", parent=base["Heading2"], textColor=colors.HexColor(_BRAND_GREEN),
            spaceBefore=14, spaceAfter=6),
        "body": ParagraphStyle("ImadBody", parent=base["BodyText"], fontSize=9.5, leading=13),
        "small": ParagraphStyle(
            "ImadSmall", parent=base["BodyText"], fontSize=8, leading=11,
            textColor=colors.HexColor("#475467")),
    }
    return colors, styles


def _pdf_header_footer(canvas, doc):
    """Shared page furniture: brand rule + footer with page numbers."""
    from reportlab.lib import colors

    canvas.saveState()
    w, h = doc.pagesize
    canvas.setStrokeColor(colors.HexColor(_BRAND_GOLD))


def build_pdf_report(path: str | Path, title: str, subtitle: str = "",
                     sections: Iterable[tuple[str, List[List[Any]], Optional[str]]] = (),
                     meta_rows: Optional[List[List[Any]]] = None,
                     summary_box: Optional[Dict[str, Any]] = None,
                     chart_drawing=None) -> Path:
    """Generic branded PDF report.

    ``sections`` yields ``(heading, table_rows, note)`` triples; the first row
    of each ``table_rows`` is the styled header row. ``summary_box`` renders a
    highlighted KPI block on the cover; ``chart_drawing`` (a reportlab Drawing)
    is appended after it when provided.
    """
    try:
        from reportlab.lib import colors
        from reportlab.lib.enums import TA_CENTER
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle
        from reportlab.platypus import (
            Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
        )
    except ImportError as exc:  # pragma: no cover
        raise ExportError("reportlab is required for PDF export") from exc

    _, styles = _pdf_styles()
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)

    story: List[Any] = [Paragraph(title, styles["title"])]
    if subtitle:
        story.append(Paragraph(subtitle, ParagraphStyle(
            "sub", parent=styles["body"], alignment=TA_CENTER, spaceAfter=10)))
    if meta_rows:
        meta = Table([[str(c) for c in row] for row in meta_rows], colWidths=[150, 330])
        meta.setStyle(TableStyle([
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        story += [Spacer(1, 6), meta]
    if summary_box:
        kpi_rows = [[k, _fmt(v)] for k, v in summary_box.items()]
        kpi = Table(kpi_rows, colWidths=[240, 150])
        kpi.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#ECFDF3")),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor(_BRAND_GREEN)),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
        ]))
        story += [Spacer(1, 12), kpi]
    if chart_drawing is not None:
        story += [Spacer(1, 12), chart_drawing]

    for heading, rows, note in sections:
        story.append(Paragraph(heading, styles["h2"]))
        if not rows:
            story.append(Paragraph("No data available.", styles["body"]))
            continue
        data = [[str(c) for c in rows[0]]] + [
            [_fmt(c) for c in row] for row in rows[1:]]
        table = Table(data, repeatRows=1)
        style = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(_BRAND_GREEN)),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#D0D5DD")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1),
             [colors.white, colors.HexColor("#F5F7FA")]),
            ("TOPPADDING", (0, 0), (-1, -1), 3.5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3.5),
        ]
        for r_i, row in enumerate(rows):
            if str(row[0]).startswith(("TOTAL", "Σ")):
                style.append(("BACKGROUND", (0, r_i), (-1, r_i),
                              colors.HexColor("#FEF6DE")))
                style.append(("FONTNAME", (0, r_i), (-1, r_i), "Helvetica-Bold"))
        table.setStyle(TableStyle(style))
        story.append(table)
        if note:
            story.append(Spacer(1, 4))
            story.append(Paragraph(note, styles["small"]))

    doc = SimpleDocTemplate(
        str(out), pagesize=A4, topMargin=58, bottomMargin=44,
        leftMargin=40, rightMargin=40, title=title)
    doc.build(story, onFirstPage=_pdf_header_footer, onLaterPages=_pdf_header_footer)
    log.info("PDF written: %s", out)
    return out


def simple_bar_chart(title: str, series: Sequence[tuple[str, float]],
                     unit: str = "", width: int = 480, height: int = 260):
    """Return a reportlab Drawing bar chart for embedding into PDF reports."""
    try:
        from reportlab.graphics.charts.barcharts import VerticalBarChart
        from reportlab.graphics.shapes import Drawing, String
        from reportlab.lib import colors
    except ImportError as exc:  # pragma: no cover
        raise ExportError("reportlab is required for charts") from exc

    d = Drawing(width, height)
    chart = VerticalBarChart()
    chart.x, chart.y, chart.width, chart.height = 55, 40, width - 80, height - 80
    chart.data = [[float(v) for _, v in series]]
    chart.categoryAxis.categoryNames = [k for k, _ in series]
    chart.categoryAxis.labels.fontName = "Helvetica"
    chart.categoryAxis.labels.fontSize = 7
    chart.valueAxis.valueMin = 0
    chart.valueAxis.valueMax = max([float(v) for _, v in series] or [1]) * 1.25
    chart.valueAxis.labels.fontName = "Helvetica"
    chart.valueAxis.labels.fontSize = 7
    chart.bars.fillColor = colors.HexColor(_BRAND_GREEN)
    chart.barLabels.fontName = "Helvetica"
    chart.barLabels.fontSize = 7
    chart.barLabelFormat = "%.0f"
    d.add(chart)
    if unit:
        d.add(String(55, height - 22, f"Values in {unit}",
                     fontName="Helvetica-Oblique", fontSize=8))
    return d


# ═══════════════════════════════════════════════════ Word (DOCX) ─────────────
_DOCX_STATUS_COLORS = {"pass": "1A7F37", "fail": "C0392B", "warn": "B7791F"}


def submission_docx(out_path: str | Path, *, project_id: int,
                    project_name: str, analysis: Dict[str, Any],
                    compliance: Dict[str, Any],
                    boq: Optional[Dict[str, Any]] = None,
                    survey: Optional[Dict[str, Any]] = None,
                    engineer_name: Optional[str] = None) -> Path:
    """Editable Word calculation note (roadmap #17) — the working companion
    to the sealed SBC 304 PDF package.

    Mirrors the PDF's content (design basis, member forces, design factors,
    clause-referenced compliance checks, BOQ totals, certification block) but
    stays data-driven: a section is written only when its backing data
    exists, so the note can never claim more than the engines computed.
    """
    try:
        from docx import Document
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.shared import RGBColor
    except ImportError as exc:  # pragma: no cover
        raise ExportError("python-docx is required for Word export") from exc

    def _txt(value: Any) -> str:
        return "—" if value in (None, "") else _fmt(value)

    out = Path(out_path)
    doc = Document()

    title = doc.add_heading("Structural Calculation Note — SBC 304", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle = doc.add_paragraph(project_name)
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in subtitle.runs:
        run.italic = True

    meta = doc.add_paragraph()
    meta.add_run(f"Project: {project_name} (#{project_id})\n").bold = True
    if engineer_name:
        meta.add_run(f"Engineer of record: {engineer_name}\n")
    meta.add_run(f"Generated by Imad · {now_iso()}\n")
    meta.add_run("Editable companion to the sealed SBC 304 PDF package — "
                 "the signed PDF remains the authoritative document.")

    def _table(headers: Sequence[str], rows: Sequence[Sequence[Any]]) -> None:
        table = doc.add_table(rows=1, cols=len(headers))
        table.style = "Table Grid"
        for cell, text in zip(table.rows[0].cells, headers):
            cell.text = str(text)
            for run in cell.paragraphs[0].runs:
                run.bold = True
        for row in rows:
            for cell, value in zip(table.add_row().cells, row):
                cell.text = _txt(value)
        doc.add_paragraph()

    # ── Design basis (survey) ──
    if survey:
        basis_rows = [
            [label, _txt(survey.get(key))]
            for label, key in (
                ("Soil bearing capacity (kPa)", "soil_bearing_capacity_kpa"),
                ("Soil type", "soil_type"),
                ("Groundwater depth (m)", "groundwater_depth_m"),
                ("Terrain slope (°)", "terrain_slope_deg"),
            )
            if survey.get(key) not in (None, "")
        ]
        if basis_rows:
            doc.add_heading("Design Basis & Site Survey", 1)
            _table(["Parameter", "Value"], basis_rows)

    # ── Member forces ──
    forces = analysis.get("member_forces") or []
    if forces:
        doc.add_heading("Member Forces & Critical Actions", 1)
        _table(
            ["Element", "Kind", "M (kN·m)", "V (kN)", "N (kN)", "Δ (mm)"],
            [[m.get("element_id"), m.get("kind"), m.get("moment_kNm"),
              m.get("shear_kN"), m.get("axial_kN"), m.get("deflection_mm")]
             for m in forces[:60]],
        )
        if len(forces) > 60:
            doc.add_paragraph(
                f"Showing the first 60 of {len(forces)} members — the full "
                "set lives in the stored analysis result.")

    return _submission_docx_tail(
        doc, out, analysis=analysis, compliance=compliance, boq=boq,
        engineer_name=engineer_name)


def _submission_docx_tail(doc: Any, out: Path, *, analysis: Dict[str, Any],
                          compliance: Dict[str, Any],
                          boq: Optional[Dict[str, Any]],
                          engineer_name: Optional[str]) -> Path:
    """Compliance / BOQ / certification sections of the Word note."""
    from docx import Document  # noqa: F401  (template types already loaded)
    from docx.shared import RGBColor

    def _txt(value: Any) -> str:
        return "—" if value in (None, "") else _fmt(value)

    def _table(headers: Sequence[str], rows: Sequence[Sequence[Any]]) -> None:
        table = doc.add_table(rows=1, cols=len(headers))
        table.style = "Table Grid"
        for cell, text in zip(table.rows[0].cells, headers):
            cell.text = str(text)
            for run in cell.paragraphs[0].runs:
                run.bold = True
        for row in rows:
            for cell, value in zip(table.add_row().cells, row):
                cell.text = _txt(value)
        doc.add_paragraph()

    # ── Strength design factors ──
    design = analysis.get("design") if isinstance(analysis.get("design"), dict) else {}
    factors = (analysis.get("design_factors") or design.get("design_factors") or {})
    if isinstance(factors, dict) and factors:
        doc.add_heading("Strength Design Factors (φ)", 1)
        factor_rows: List[List[Any]] = []
        for name, spec in factors.items():
            if isinstance(spec, dict):
                factor_rows.append([name, spec.get("value"), spec.get("clause", "")])
            else:
                factor_rows.append([name, spec, ""])
        _table(["Factor", "Value", "Clause"], factor_rows)

    # ── Design utilization ──
    members = design.get("members") or []
    util_rows: List[List[Any]] = []
    if design.get("max_utilization") is not None:
        util_rows.append(["Max utilization", _txt(design.get("max_utilization"))])
    if members:
        worst = max(members, key=lambda m: float(m.get("utilization") or 0.0))
        util_rows.append(["Governing member", f"{worst.get('id', '—')} — "
                          f"{worst.get('governing_check', '—')}"])
    if util_rows:
        doc.add_heading("Design Utilization", 1)
        _table(["Metric", "Value"], util_rows)

    # ── Analysis summary ──
    summary = analysis.get("summary")
    if isinstance(summary, dict) and summary:
        doc.add_heading("Analysis Summary", 1)
        _table(["Metric", "Value"], [[k, _txt(v)] for k, v in summary.items()])

    # ── Code compliance ──
    checks = compliance.get("checks") or []
    if checks:
        doc.add_heading(f"Code Compliance — {compliance.get('code_name', 'SBC 304')}", 1)
        status_color = {"pass": "0A5C36", "warn": "B45309", "fail": "B91C1C"}
        table = doc.add_table(rows=1, cols=4)
        table.style = "Table Grid"
        for cell, text in zip(table.rows[0].cells,
                              ["Check", "Clause", "Status", "Details"]):
            cell.text = str(text)
            for run in cell.paragraphs[0].runs:
                run.bold = True
        for c in checks:
            details = c.get("details") or {}
            note = details.get("note") or details.get("message") or ""
            cells = table.add_row().cells
            for cell, value in zip(cells, [c.get("check_name"),
                                           details.get("clause", ""),
                                           str(c.get("status", "")).upper(), note]):
                cell.text = _txt(value)
            color = status_color.get(str(c.get("status", "")).lower())
            if color:
                cells[2].text = ""
                run = cells[2].paragraphs[0].add_run(str(c.get("status", "")).upper())
                run.bold = True
                run.font.color.rgb = RGBColor.from_string(color)
        doc.add_paragraph()
        s = compliance.get("summary") or {}
        doc.add_paragraph(f"{s.get('passed', 0)} passed · {s.get('failed', 0)} failed · "
                          f"{s.get('warned', 0)} warnings.")

    # ── Preliminary BOQ ──
    if boq:
        totals = boq.get("totals") or {}
        doc.add_heading("Preliminary Bill of Quantities", 1)
        _table(["Metric", "Value"], [
            ["Total estimate (USD)", _txt(totals.get("amount_usd"))],
            ["Cost / m² (USD)", _txt(totals.get("amount_per_m2"))],
            ["Rebar total (kg)", _txt(totals.get("rebar_kg"))],
        ])
        items = boq.get("items") or []
        if items:
            _table(["Code", "Description", "Unit", "Qty", "Rate USD", "Amount USD"],
                   [[i.get("code"), i.get("description"), i.get("unit"),
                     i.get("quantity"), i.get("rate"), i.get("amount_usd")]
                    for i in items])

    # ── Certification block ──
    doc.add_heading("Certification", 1)
    doc.add_paragraph(
        "This calculation note is an editable companion to the sealed SBC 304 "
        "PDF package. The signed PDF remains the authoritative document for "
        "municipality submission; this note exists so the engineer of record "
        "can review, annotate and extend the calculations.")
    doc.add_paragraph(
        f"Engineer of record: {engineer_name or '— pending signature —'}")
    doc.add_paragraph("Signature: ______________________    "
                      "License no.: ______________________    "
                      "Date: ______________")

    doc.save(out)
    return out